datasource:
  mysql:
    type: mysql
    host: 114.55.145.3
    port: 23333
    username: root
    password: wjyy26303
    database: canyon-v2
  mongodb:
    type: mongodb
    host: 127.0.0.1
    port: 27017
    username: root
    password: root
    database: canyon

gitlab:
  application:
    clientId: clientId
    clientSecret: clientSecret
    redirectUri: redirectUri
    uri: uri

